Repository slackapi/slack-cli, pull requests merged in 2025-06, with the labels that each got.

#110 refactor: loop over a range of integers starting from zero in shorthand
  internal/api/icon_test.go
  internal/hooks/hook_executor_v2.go
Labels: code health, semver:patch

#125 build: share releases of feature tags for install from pull requests
  .circleci/config.yml
  .github/MAINTAINERS_GUIDE.md
  .github/workflows/delete-pr-build-on-close.yml
Labels: semver:patch, build

#126 feat: include target architecture of compiled builds in logstash events
  internal/tracking/logstash_event.go
  internal/tracking/tracking.go
  internal/tracking/tracking_test.go
Labels: enhancement, semver:patch

#135 docs: surround remediation flags with backticks for prompted feedback
  internal/slackerror/errors.go
Labels: docs, semver:patch

#127 build(vscode): cleanup the debug launch configuration
  .vscode/launch.json
Labels: semver:patch, build

#130 refactor(config): destructify config.GetProjectDirPath(fs, os)
  internal/config/project.go
  internal/config/project_mock.go
  internal/config/project_test.go
  internal/slackdeps/os_mock.go
Labels: code health, semver:patch

#132 fix: 'run' exiting on disconnected api errors when streaming activity logs
  internal/api/activity.go
  internal/api/client.go
  internal/pkg/platform/activity.go
  internal/pkg/platform/activity_test.go
Labels: bug, changelog, semver:patch

#138 refactor(config): destructify project-level getter and setters in package config
  .vscode/settings.json
  cmd/app/link.go
  cmd/app/link_test.go
  cmd/doctor/check.go
  cmd/doctor/check_test.go
  cmd/doctor/doctor_test.go
  internal/app/app_client.go
  internal/app/app_client_test.go
  internal/config/experiments.go
  internal/config/project.go
  internal/config/project_mock.go
  internal/config/project_test.go
  internal/pkg/create/create.go
  test/slackmock/slackmock.go
Labels: code health, semver:patch

#139 feat: include bolt for javascript and python in the 'samples' command
  cmd/feedback/feedback.go
  cmd/project/create_samples.go
  cmd/project/create_samples_test.go
  cmd/project/samples.go
  cmd/project/samples_test.go
  internal/iostreams/survey.go
Labels: enhancement, changelog, semver:minor

#140 feat: accept the app name as an argument to the 'samples' command
  cmd/project/samples.go
  cmd/project/samples_test.go
Labels: bug, changelog, semver:minor
