Repository slackapi/slack-cli, pull requests merged in 2025-09, with the labels that each got.

#228 build: make releases with a "make tag" build command
  Makefile
Labels: docs, code health, semver:patch, build

#174 docs: add hooks specification to the sidebar
  .github/cli-sdk-specification.md
  docs/_sidebar.json
  docs/reference/hooks/index.md
Labels: docs, semver:patch

#229 build: run the docgen command with make tag release
  Makefile
Labels: code health, semver:patch

#192 feat: output a list of samples for a language with the samples command
  cmd/project/create_samples.go
  cmd/project/create_samples_test.go
  cmd/project/create_template.go
  cmd/project/samples.go
  cmd/project/samples_test.go
Labels: enhancement, changelog, semver:minor, area:deno-sdk, area:bolt-js, area:bolt-python

#193 feat: deprecate the "branch" and "template" flag for the samples command
  .github/MAINTAINERS_GUIDE.md
  cmd/project/samples.go
Labels: enhancement, changelog, code health, semver:patch

#232 docs: fix broken link to removing an app pages
  docs/guides/uninstalling-the-slack-cli.md
Labels: docs
