Repository slackapi/slack-cli, pull requests merged in 2025-08, with the labels that each got.

#175 fix: order authentications by team domain in doctor command outputs
  cmd/doctor/check.go
  cmd/doctor/check_test.go
  cmd/doctor/doctor_test.go
Labels: bug, changelog, semver:patch

#183 docs: update tools.slack.dev refs to docs.slack.dev/tools
  .github/MAINTAINERS_GUIDE.md
  .github/cli-sdk-specification.md
  cmd/datastore/datastore.go
  cmd/env/env.go
  cmd/externalauth/externalauth.go
  cmd/function/function.go
  cmd/help/help.go
  cmd/project/create.go
  cmd/root.go
  cmd/triggers/generate.go
  docs/reference/commands/slack.md
  docs/reference/commands/slack_datastore.md
  docs/reference/commands/slack_env.md
  docs/reference/commands/slack_external-auth.md
  docs/reference/commands/slack_function.md
  internal/slackerror/errors.go
  internal/update/cli.go
  scripts/install-dev.sh
  scripts/install-windows-dev.ps1
  scripts/install-windows.ps1
  scripts/install.sh
Labels: docs, changelog, semver:patch

#154 feat(bolt-install): support using 'install' command with remote manifests
  cmd/app/add.go
  cmd/app/add_test.go
  cmd/platform/deploy.go
  cmd/platform/deploy_test.go
  cmd/triggers/create.go
  docs/reference/experiments.md
  internal/pkg/apps/install.go
  internal/pkg/apps/install_test.go
Labels: docs, enhancement, changelog, semver:minor, area:bolt-js, area:bolt-python

#167 feat: error if the runtime is not found with a missing hook
  cmd/root.go
  cmd/root_test.go
  cmd/triggers/create.go
  cmd/triggers/create_test.go
  internal/slackerror/errors.go
Labels: enhancement, changelog, semver:patch

#172 test: run the windows and unix test suites on release tags
  .circleci/config.yml
Labels: code health, semver:patch, build

#185 fix: URL checker uses HEAD instead of GET
  internal/deputil/url.go
  internal/deputil/url_test.go
  internal/pkg/create/create_test.go
  internal/slackhttp/http.go
  internal/slackhttp/http_mock.go
Labels: bug, changelog, semver:patch

#194 fix: generate documentation without template literals and with standard headers
  cmd/docgen/docgen.go
  cmd/docgen/docgen_test.go
  internal/shared/clients.go
  internal/shared/clients_mock.go
  internal/slackdeps/cobra_mock.go
  internal/slackerror/errors.go
Labels: bug, docs, semver:patch

#189 feat: remove deno from installation scripts
  .github/workflows/tests.yml
  Makefile
  docs/guides/authorizing-the-slack-cli.md
  docs/guides/installing-the-slack-cli-for-mac-and-linux.md
  docs/guides/installing-the-slack-cli-for-windows.md
  scripts/install-dev-test.sh
  scripts/install-dev.sh
  scripts/install-test.sh
  scripts/install-windows-dev.ps1
  scripts/install-windows.ps1
  scripts/install.sh
Labels: docs, enhancement, changelog, code health, semver:minor, build
