Repository slackapi/slack-cli, pull requests merged in 2025-04, with the labels that each got.

#23 docs(readme): remove token from CircleCI status badge after open source
  README.md
Labels: documentation, semver:patch

#27 docs: fix sync issue by updating README.md logo to use GitHub URL
  README.md
Labels: docs, semver:patch

#26 chore: group documentation in release notes using the 'docs' label
  .github/MAINTAINERS_GUIDE.md
  .github/release.yml
Labels: docs, semver:patch

#24 test: mock context in TableTestCommand.ExpectedAsserts
  cmd/app/add_test.go
  cmd/app/delete_test.go
  cmd/app/link_test.go
  cmd/auth/login_test.go
  cmd/auth/logout_test.go
  cmd/auth/revoke_test.go
  cmd/collaborators/add_test.go
  cmd/collaborators/remove_test.go
  cmd/collaborators/update_test.go
  cmd/datastore/bulk_put_test.go
  cmd/datastore/count_test.go
  cmd/datastore/query_test.go
  cmd/docgen/docgen_test.go
  cmd/env/add_test.go
  cmd/env/list_test.go
  cmd/env/remove_test.go
  cmd/externalauth/add_secret_test.go
  cmd/externalauth/add_test.go
  cmd/externalauth/remove_test.go
  cmd/externalauth/select_auth_test.go
  cmd/function/access_test.go
  cmd/manifest/info_test.go
  cmd/manifest/manifest_test.go
  cmd/openformresponse/export_test.go
  cmd/project/init_test.go
  cmd/project/samples_test.go
  cmd/triggers/access_test.go
  cmd/triggers/create_test.go
  cmd/triggers/delete_test.go
  cmd/triggers/info_test.go
  cmd/triggers/list_test.go
  cmd/triggers/update_test.go
  internal/pkg/platform/activity_test.go
  test/testutil/commandtests.go
Labels: code health, semver:patch

#29 ci: adds workflow for syncing docs out to docusaurus repo
  .github/workflows/sync-docs-from-cli-repo.yml
Labels: docs, semver:patch

#28 test: use slackcontext.MockContext(...) instead of context.Background()
  cmd/app/link_test.go
  cmd/app/uninstall_test.go
  cmd/auth/token_test.go
  cmd/doctor/check_test.go
  cmd/doctor/doctor_test.go
  cmd/env/add_test.go
  cmd/feedback/feedback_test.go
  cmd/function/access_test.go
  cmd/function/prompt_test.go
  cmd/help/help_test.go
  cmd/platform/deploy_test.go
  cmd/project/create_samples_test.go
  cmd/project/create_test.go
  cmd/project/init_test.go
  cmd/triggers/create_test.go
  cmd/triggers/generate_test.go
  internal/app/app_client_test.go
  internal/app/manifest_test.go
  internal/cache/manifest_test.go
  internal/cmdutil/project_test.go
  internal/config/config_test.go
  internal/config/project_test.go
  internal/config/system_test.go
  internal/iostreams/logfile_test.go
  internal/iostreams/printer_test.go
  internal/iostreams/survey_test.go
  internal/pkg/apps/delete_test.go
  internal/pkg/apps/install_test.go
  internal/pkg/apps/list_test.go
  internal/pkg/auth/list_test.go
  internal/pkg/create/create_test.go
  internal/pkg/datastore/bulk_delete_test.go
  internal/pkg/datastore/bulk_get_test.go
  internal/pkg/datastore/bulk_put_test.go
  internal/pkg/datastore/delete_test.go
  internal/pkg/datastore/get_test.go
  internal/pkg/datastore/put_test.go
  internal/pkg/datastore/query_test.go
  internal/pkg/datastore/update_test.go
  internal/pkg/externalauth/prompt_provider_auth_select_test.go
  internal/pkg/externalauth/prompt_provider_select_test.go
  internal/pkg/externalauth/prompt_token_select_test.go
  internal/pkg/externalauth/prompt_workflow_select_test.go
  internal/pkg/manifest/validate_test.go
  internal/pkg/platform/activity_test.go
  internal/pkg/platform/localserver_test.go
  internal/prompts/app_select_test.go
  internal/runtime/deno/deno_test.go
  internal/runtime/node/node_test.go
  internal/runtime/node/npm_test.go
  internal/runtime/python/python_test.go
  internal/runtime/runtime_test.go
  internal/shared/clients_test.go
  internal/slackcontext/slackcontext_test.go
  internal/update/cli_metadata_test.go
Labels: code health, semver:patch

#30 ci: attempt deletion of branch prereleases from prior versions on merge
  .github/workflows/delete-pr-build-on-close.yml
Labels: semver:patch, build

#37 build: set the complete semver version of github action steps
  .github/workflows/dependencies.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/license_check.yml
  .github/workflows/sync-docs-from-cli-repo.yml
  .github/workflows/tests.yml
Labels: semver:patch, build

#33 refactor: update .Context() references for consistency
  cmd/app/app.go
  cmd/app/link_test.go
  cmd/auth/list.go
  cmd/auth/login.go
  cmd/collaborators/add.go
  cmd/collaborators/list.go
  cmd/collaborators/remove.go
  cmd/collaborators/update.go
  cmd/doctor/doctor_test.go
  cmd/fingerprint/fingerprint.go
  cmd/help/help.go
  cmd/platform/deploy.go
  cmd/platform/run.go
  cmd/project/create.go
  cmd/project/create_template.go
  cmd/root.go
  cmd/root_test.go
  cmd/triggers/access.go
  cmd/triggers/create.go
  cmd/triggers/info.go
  cmd/triggers/list.go
  cmd/upgrade/upgrade.go
  cmd/version/version.go
  internal/config/project_test.go
  internal/slacktrace/slacktrace.go
  internal/update/cli.go
  internal/update/sdk.go
  internal/update/sdk_test.go
  internal/update/update.go
  main.go
Labels: code health, semver:patch

#34 docs: update Slack CLI and Install Scripts to use the new https://slack.dev docs
  .github/MAINTAINERS_GUIDE.md
  .github/cli-sdk-specification.md
  cmd/datastore/datastore.go
  cmd/env/env.go
  cmd/externalauth/externalauth.go
  cmd/function/function.go
  cmd/help/help.go
  cmd/project/create.go
  cmd/project/create_template.go
  cmd/project/samples.tmpl
  cmd/root.go
  cmd/triggers/generate.go
  cmd/upgrade/upgrade.go
  internal/api/client.go
  internal/shared/types/channel.go
  internal/shared/types/team.go
  internal/shared/types/user.go
  internal/slackerror/errors.go
  internal/update/cli.go
  scripts/install-dev.sh
  scripts/install-windows-dev.ps1
  scripts/install-windows.ps1
  scripts/install.sh
Labels: docs, changelog, semver:patch

#38 ci: escape pull request branch tag before creating releases to test
  .circleci/config.yml
Labels: semver:patch, build

#36 ci: report test status to changes made from a forked branch
  .github/MAINTAINERS_GUIDE.md
  .github/workflows/e2e_tests.yml
Labels: semver:patch, build

#45 refactor: remove context.Background() references from create and deploy
  cmd/project/create_template.go
  internal/pkg/platform/deploy.go
Labels: code health, semver:patch

#40 ci: delete pre-releases matching existing or escaped tags
  .github/workflows/delete-pr-build-on-close.yml
Labels: semver:patch, build

#47 refactor: remove context.Background() references from triggers command
  cmd/triggers/create.go
  cmd/triggers/create_test.go
  cmd/triggers/generate.go
  cmd/triggers/generate_test.go
  cmd/triggers/update.go
Labels: code health, semver:patch

#48 ci: delete testing fork pre-releases using upstream tag names
  .github/workflows/delete-pr-build-on-close.yml
Labels: semver:patch, build

#35 docs: fix misspellings (used typos-cli for detecting)
  ci/circleci/runner/src/circlerunner.py
  ci/circleci/runner/src/macrunner.py
  cmd/auth/login_test.go
  cmd/datastore/query_test.go
  cmd/manifest/validate.go
  cmd/project/create_samples.go
  internal/api/workflows_test.go
  internal/app/app.go
  internal/app/app_client_test.go
  internal/cmdutil/flags.go
  internal/config/manifest_test.go
  internal/config/system_test.go
  internal/hooks/script_test.go
  internal/iostreams/reader.go
  internal/logger/logevent.go
  internal/pkg/apps/install.go
  internal/pkg/platform/activity_test.go
  internal/prompts/app_select.go
  internal/prompts/app_select_test.go
  internal/slackerror/error.go
  internal/update/autoupdate_test.go
  internal/update/cli_autoupdate.go
Labels: docs, semver:patch, cla:signed

#46 fix: 'upgrade' output includes SDK when inside a project dir
  cmd/upgrade/upgrade.go
Labels: bug, semver:patch

#52 ci: use different tokens to update docs and go version
  .github/MAINTAINERS_GUIDE.md
  .github/workflows/dependencies.yml
  .github/workflows/sync-docs-from-cli-repo.yml
  docs/guides/authorizing-the-slack-cli.md
Labels: semver:patch, build

#55 ci: update upstream documentation if the event referenced on the main branch
  .github/workflows/sync-docs-from-cli-repo.yml
  docs/guides/deploying-with-the-slack-cli-and-github-actions.md
Labels: docs, semver:patch, build

#57 refactor: rename root.Execute to root.ExecuteContext
  cmd/root.go
  main.go
Labels: code health, semver:patch

#53 ci: use environment variables to process pull request conclusions
  .github/workflows/delete-pr-build-on-close.yml
Labels: security, semver:patch, build

#54 ci: set minimum amount of permission needed for each workflow
  .github/workflows/delete-pr-build-on-close.yml
  .github/workflows/dependencies.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/license_check.yml
  .github/workflows/sync-docs-from-cli-repo.yml
  .github/workflows/tests.yml
Labels: security, semver:patch, build

#59 build: remove paths to outdated artifacts in makefile clean
  Makefile
Labels: code health, semver:patch, build

#62 docs: add comment block to package slackcontext
  internal/slackcontext/slackcontext.go
Labels: docs, semver:patch

#60 fix: edge-case where cancelled context causes process to hang
  cmd/root.go
Labels: bug, changelog, semver:patch

#61 test: add success and error tests to cmd.ExecuteContext
  cmd/root.go
  cmd/root_test.go
Labels: code health, semver:patch

#64 test: assert cmd.ExecuteContext flushes exit code to logstash
  cmd/root_test.go
  internal/iostreams/iostreams_mock.go
  internal/shared/clients_mock.go
  internal/tracking/tracking_mock.go
Labels: code health, semver:patch

#66 feat: update 'feedback' command to include feedback about the Slack CLI
  cmd/feedback/feedback.go
  cmd/feedback/feedback_test.go
Labels: enhancement, changelog, semver:minor

#67 test: fix failing version tests if compilation flags are not provided
  cmd/root_test.go
  internal/pkg/version/version.go
Labels: code health, semver:patch
