Repository slackapi/slack-cli, pull requests merged in 2025-05, with the labels that each got.

#68 refactor: 'feedback' command trace and error handling
  cmd/feedback/feedback.go
  cmd/feedback/feedback_test.go
  internal/slackerror/errors.go
Labels: changelog, code health, semver:patch

#70 feat: add support for 'feedback --name slack-platform'
  cmd/feedback/feedback.go
  cmd/feedback/feedback_test.go
Labels: enhancement, changelog, semver:minor

#76 refactor: enable linter rule ST1008 for 'error should be last return value'
  .golangci.yml
  cmd/auth/login.go
  cmd/root.go
  cmd/root_test.go
  internal/cmdutil/project.go
  internal/hooks/sdk_config.go
  internal/hooks/sdk_config_test.go
Labels: code health, semver:patch

#73 refactor: enable linter rule ST1005 for error string formatting
  .golangci.yml
  internal/api/client.go
  internal/auth/auth.go
  internal/pkg/create/create.go
  internal/pkg/platform/localserver.go
  internal/style/template.go
  internal/update/cli_metadata.go
Labels: code health, semver:patch

#74 docs: add docs for deprecating a feature
  .github/MAINTAINERS_GUIDE.md
  internal/config/project.go
  internal/pkg/create/create_test.go
  internal/shared/clients.go
Labels: docs, semver:patch

#81 refactor: rename clients.AuthInterface() to clients.Auth()
  cmd/app/add_test.go
  cmd/app/delete_test.go
  cmd/app/link.go
  cmd/app/link_test.go
  cmd/app/uninstall_test.go
  cmd/auth/login_test.go
  cmd/auth/logout.go
  cmd/auth/logout_test.go
  cmd/auth/revoke.go
  cmd/auth/revoke_test.go
  cmd/auth/token_test.go
  cmd/doctor/check.go
  cmd/doctor/doctor_test.go
  cmd/manifest/validate.go
  cmd/manifest/validate_test.go
  cmd/project/init_test.go
  cmd/root.go
  internal/pkg/apps/delete.go
  internal/pkg/apps/delete_test.go
  internal/pkg/apps/list.go
  internal/pkg/apps/list_test.go
  internal/pkg/auth/list.go
  internal/pkg/auth/list_test.go
  internal/pkg/auth/login.go
  internal/pkg/platform/deploy.go
  internal/prompts/app_select.go
  internal/prompts/app_select_test.go
  internal/shared/clients.go
  internal/shared/clients_mock.go
  main.go
Labels: code health, semver:patch

#86 refactor: enable linter rule ST1016 for 'consistent method receiver names'
  .golangci.yml
  internal/iostreams/iostreams_mock.go
  internal/prompts/app_select.go
  internal/slackdeps/os.go
Labels: code health, semver:patch

#88 feat(bolt-install): added --experiment=bolt-install
  cmd/app/add_test.go
  cmd/manifest/info_test.go
  docs/guides/using-slack-cli-with-bolt-frameworks.md
  docs/reference/experiments.md
  internal/experiment/experiment.go
  internal/pkg/apps/install_test.go
Labels: enhancement, changelog, experiment, semver:patch

#89 refactor: enable linter rule QF1011 for 'Omit redundant types from declaration'
  .golangci.yml
  internal/auth/auth.go
  internal/config/system.go
  internal/iostreams/logfile.go
  internal/iostreams/survey.go
  internal/pkg/auth/login.go
Labels: code health, semver:patch

#91 fix: parse the latest deno release in installation script outputs as a tagged version
  scripts/install-dev.sh
  scripts/install.sh
Labels: bug, changelog, semver:patch, cla:signed

#90 feat: display manifest source in human-friendly format
  cmd/app/link.go
  cmd/project/init_test.go
  internal/config/manifest.go
  internal/config/manifest_test.go
  internal/pkg/create/create.go
  internal/pkg/create/create_test.go
Labels: enhancement, changelog, semver:patch

#94 test: confirm the check for dev apihosts does not match production or qa
  internal/auth/auth_test.go
Labels: code health, semver:patch

#93 fix: include the top level app command with sub commands in help page examples
  cmd/app/app.go
Labels: bug, docs, changelog, semver:patch

#92 feat: add 'app settings' command to open app settings webpage for a selected app
  cmd/app/app.go
  cmd/app/settings.go
  cmd/app/settings_test.go
  internal/slackerror/errors.go
  internal/slacktrace/slacktrace.go
Labels: enhancement, changelog, semver:minor

#95 refactor: enable linter rule QF1008 for 'Omit embedded fields from selector expression'
  .golangci.yml
  cmd/triggers/update.go
  internal/api/activity.go
  internal/api/app_test.go
  internal/api/auth.go
  internal/api/datastore.go
  internal/api/workflows.go
  internal/cache/manifest.go
  internal/cache/manifest_test.go
  internal/pkg/apps/install.go
  internal/pkg/platform/deploy.go
Labels: code health, semver:patch

#99 refactor: enable linter rule QF1004 for 'Use strings.ReplaceAll when possible'
  .golangci.yml
  internal/pkg/create/create.go
Labels: code health, semver:patch

#100 ci: pin action hashes and escape variables with minimum permission
  .github/workflows/delete-pr-build-on-close.yml
  .github/workflows/dependencies.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/license_check.yml
  .github/workflows/sync-docs-from-cli-repo.yml
  .github/workflows/tests.yml
Labels: code health, security, semver:patch

#105 refactor: enable linter rule ST1023 for 'Redundant type in variable declaration'
  .golangci.yml
Labels: code health, semver:patch

#104 test: add tests for slackdeps.NewFs()
  internal/slackdeps/fs_test.go
Labels: code health, semver:patch

#101 build: package for apple intel and apple silicon machines alongside universal binaries as fallback
  .circleci/config.yml
  .github/MAINTAINERS_GUIDE.md
  .goreleaser-dev.yml
  .goreleaser.yml
  internal/update/cli_autoupdate.go
  internal/update/cli_autoupdate_test.go
  scripts/install-dev.sh
  scripts/install.sh
Labels: enhancement, changelog, semver:minor, build

#102 test: fix tests to run in airplane mode (offline)
  internal/deputil/url.go
  internal/deputil/url_test.go
  internal/pkg/create/create.go
  internal/pkg/create/create_test.go
  internal/slackhttp/http.go
  internal/slackhttp/http_mock.go
  internal/slackhttp/http_test.go
Labels: code health, semver:patch

#103 fix: removing .git from inside git template urls
  internal/pkg/create/create.go
  internal/pkg/create/create_test.go
Labels: bug, changelog, semver:patch

#112 feat(bolt-install): enable bolt-install experiment by default
  docs/reference/experiments.md
  internal/experiment/experiment.go
  internal/pkg/apps/install_test.go
  internal/pkg/create/create.go
Labels: enhancement, changelog, experiment, semver:minor
